Blood_blog/urls.py
from django.urls import path,include, re_path
from . import views

app_name='Blood_blog'
urlpatterns = [
    path('home/',views.Home,name="home"),
    path('form/',views.DonationFormView,name="DonationFormView"),
    path('thankyou/',views.thankyou,name="Blood_blog.thankyou"),
    path('blog/',views.Blog,name="Blog"),
    path('blog/<int:pk>',views.detail,name="Blog-detail"),
    path('blog2/',views.Blog2,name="Blog2"),

]

Donation_Kart/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import (PasswordResetView,PasswordResetDoneView,PasswordResetConfirmView,PasswordResetCompleteView)
from login import views
import userlogin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('bcamp/',include('bcamp.urls')),
    path('Bloodblog/',include('Blood_blog.urls')),
    path('userlogin/', include('userlogin.urls')),
    path('signup/',userlogin.views.signup,name="userlogin.signup"),
    path('login/',views.user_login,name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='login/home.html'),name='logout'),
    path('reset-password/', PasswordResetView.as_view(template_name='userlogin/password_reset_form.html',
                                                        email_template_name="userlogin/reset_password_email.html",
                                                        success_url="done/"), name="password_reset"),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='userlogin/password_reset_done.html'),
        name="password_reset_done"),
    path('reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/',
        PasswordResetConfirmView.as_view(template_name="userlogin/password_reset_confirm.html"),
        name="password_reset_confirm"),
    path(r'reset-password/complete/',
        PasswordResetCompleteView.as_view(template_name="userlogin/password_reset_complete.html"),
        name="password_reset_complete"),
    path('foodtruck/', include('foodtruck.urls')),
    # path('verf/', include('admin.urls')),
    path('Personal/',include('customer.urls')),
    path('User/',include('User.urls')),
    path('verf/', include('verifier.urls')),
    path('forum/', include('forum.urls')),
    path('reliffunds/', include('funds.urls')),
    path('paytm/', include('paytm.urls')),
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

User/urls.py
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from customer import views as cust

app_name='User'

urlpatterns = [
    path('home/',views.home,name="home"),
    path('events/',views.events,name="events"),
    path('cart/',views.cart,name="cart"),
    path('proceed/',views.proceed,name="proceed"),
    path('delete/<id>',views.delete,name="delete"),
    path('events/<id>',views.filter,name="filter"),
    path('Raiserequest/',views.Raiserequest,name="Raiserequest"),
    path('natdis/',views.natdis,name="natdis")
]

Blood_blog/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

Blood_Groups = (
    ('A+', 'A+'),
    ('A-', 'A-'),
    ('B+', 'B+'),
    ('B-', 'B-'),
    ('O+', 'O+'),
    ('O-', 'O-'),
    ('AB+', 'AB+'),
    ('AB-', 'AB-'),
)

States = (
    ('Andhra Pradesh', 'Andhra Pradesh'),
    ('Arunachal Pradesh', 'Arunachal Pradesh'),
    ('Assam', 'Assam'),
    ('Bihar', 'Bihar'),
    ('Goa', 'Goa'),
    ('Haryana', 'Haryana'),
    ('Himachal Pradesh', 'Himachal Pradesh'),
    ('Jammu and Kashmir', 'Jammu and Kashmir'),
    ('Jharkhand', 'Jharkhand'),
    ('karnataka', 'karnataka'),
    ('Kerala', 'Kerala'),
    ('Madhya Pradesh', 'Madhya Pradesh'),
    ('Maharashtra', 'Maharashtra'),
    ('Manipur', 'Manipur'),
    ('Meghalaya', 'Meghalaya'),
    ('Mizoram', 'Mizoram'),
    ('Nagaland', 'Nagaland'),
    ('Odisha', 'Odisha'),
    ('Punjab', 'Punjab'),
    ('Rajasthan', 'Rajasthan'),
    ('Sikkim', 'Sikkim'),
    ('Tamil Nadu', 'Tamil Nadu'),
    ('Goa', 'Goa'),
    ('Telangana', 'Telangana'),
    ('Tripura', 'Tripura'),
    ('Uttar Pradesh', 'Uttar Pradesh'),
    ('Uttarakhand', 'Uttarakhand'),
    ('West Bengal', 'West Bengal'),
)

Hospitals = (
    ('Andhra Pradesh', ('Yashodha','Apollo')),
    ('Arunachal Pradesh',('Yashodha','Apollo')),
    ('Assam',('Yashodha','Apollo')),
    ('Bihar',('Yashodha','Apollo')),
    ('Goa', ('Yashodha','Apollo')),
    ('Haryana', ('Yashodha','Apollo')),
    ('Himachal Pradesh', ('Yashodha','Apollo')),
    ('Jammu and Kashmir', ('Yashodha','Apollo')),
    ('Jharkhand', ('Yashodha','Apollo')),
    ('karnataka', ('Yashodha','Apollo')),
    ('Kerala', ('Yashodha','Apollo')),
    ('Madhya Pradesh', ('Yashodha','Apollo')),
    ('Maharashtra', ('Yashodha','Apollo')),
    ('Manipur', ('Yashodha','Apollo')),
    ('Meghalaya', ('Yashodha','Apollo')),
    ('Mizoram', ('Yashodha','Apollo')),
    ('Nagaland', ('Yashodha','Apollo')),
    ('Odisha', ('Yashodha','Apollo')),
    ('Punjab', ('Yashodha','Apollo')),
    ('Rajasthan', ('Yashodha','Apollo')),
    ('Sikkim', ('Yashodha','Apollo')),
    ('Tamil Nadu', ('Yashodha','Apollo')),
    ('Goa', ('Yashodha','Apollo')),
    ('Telangana', ('Yashodha','Apollo')),
    ('Tripura', ('Yashodha','Apollo')),
    ('Uttar Pradesh', ('Yashodha','Apollo')),
    ('Uttarakhand', ('Yashodha','Apollo')),
    ('West Bengal', ('Yashodha','Apollo')),
)

class Comments(models.Model):
    user_comment = models.ForeignKey(User,on_delete=models.CASCADE)
    comment = models.TextField(blank = True)
    blog_id = models.PositiveIntegerField()

    def __str__(self):
        return self.comment


class Donate_blood(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    Patient_name = models.CharField(max_length=100)
    blood = models.CharField(max_length=10, choices=Blood_Groups, blank=False)
    phone_number = models.CharField(max_length=10,
                                    validators=[
                                        RegexValidator(
                                            regex='^[1-9]{1}[0-9]{9}$',
                                            message='Enter a valid phone number',
                                            code='invalid_cell'
                                        ),
                                    ]
                                    )
    gender = models.CharField(max_length=10,default='Male')
    state = models.CharField(max_length=30, choices=States, blank=False)
    Amount_blood = models.PositiveIntegerField(default = 0)
    reason = models.TextField(blank=False, null=False, max_length=500)
    date = models.DateField(default=timezone.now)
    verified = models.CharField(max_length= 5,default = "F")
    img = models.ImageField(default = "/home/hemanth/Pictures/profile_pic1.jpeg",upload_to='blog_pics')

    def __str__(self):
        return self.Patient_name

    def checkingrequestor(self):
        return '%s' % (self.user)

    def get_absolute_url(self):
        return reverse('Blog-detail',kwargs = {'id' : self.id })

Blood_blog/forms.py
from .models import *
from django.forms import ModelForm
import datetime

Blood_blog/views.py
from django.shortcuts import render
from .models import Donate_blood,Comments
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required


def Home(request):
    return render(request,'Blood_blog/home.html')

def Blog(request):
    blogs = Donate_blood.objects.raw('''select id,Patient_name,phone_number,blood,Amount_blood,date from Blood_blog_donate_blood''')


    dicts = {
        'blogs' : blogs,
    }
    return render(request,'Blood_blog/blog.html',dicts)

def Blog2(request):
    blogs = Donate_blood.objects.raw('''select id,Patient_name,phone_number,blood,Amount_blood,date from Blood_blog_donate_blood''')
    blogs1= Donate_blood.objects.raw('''select id,Patient_name,phone_number,blood,Amount_blood,date from Blood_blog_donate_blood order by date limit 3''')
    dicts = {
        'blogs' : blogs,
        'blogs1' : blogs1
    }
    return render(request,'Blood_blog/index.html',dicts)

@login_required
def detail(request,pk):
    if pk:
        if request.method == "POST":
            user = request.user
            comment = request.POST['comment']
            cmnt = Comments(user_comment = user,comment = comment, blog_id = pk)
            cmnt.save()
        blog = Donate_blood.objects.raw('''select * from Blood_blog_donate_blood where id = {0}'''.format(pk))
        for b in blog:
            print(b)
        comments = Comments.objects.raw('''select * from Blood_blog_comments where blog_id = {0}'''.format(pk))
        return render(request,'Blood_blog/Detail.html',{'blogs' :blog ,'cmnts':comments})


@login_required
def DonationFormView(request):

    user = request.user
    if request.method == "POST":
        p_name = request.POST.get('name')
        reason = request.POST.get('reason')
        state = request.POST.get('state')
        blood = request.POST.get('blood')
        date = request.POST.get('date')
        phone = request.POST.get('phone')
        Amnt = request.POST.get('Amount')
        gender = request.POST.get('gender')
        img = request.POST.get('pic')
        form1 = Donate_blood(user=user,Patient_name=p_name,blood=blood,phone_number=phone,gender=gender,state=state,Amount_blood=Amnt,reason=reason,date=date,img=img)
        form1.save()
        return render(request,'Blood_blog/thank_you.html')
    else:
        return render(request,'Blood_blog/Request_form.html')
    return render(request,'Blood_blog/Request_form.html')

def thankyou(request):
    return render(request,'Blood_blog/thank_you.html')

templates/Blood_blog/Detail.html
{% extends 'Blood_blog/base1.html' %}
{% block content%}
  {% for blog in blogs %}
    <div class="jumbotron" style = "padding-top:13px !important">
      <div class="media-body">
        <div class="article-metadata">

          {{ blog.Patient_name }}
          <small class="text-muted">{{ blog.blood }}</small>
        </div>
        <h2>{{ blog.phone_number }}</h2>
        <p class="article-content">{{ blog.Amount_blood }} ltrs</p>
      </div>
    </div>
  {% endfor %}
    <form method='POST'>
      {% csrf_token %}
      <input type="text" name="comment" placeholder="comment here...">
      <button>submit</button>
    </form>
    {% for cmnt in cmnts %}
      <ul>
        <li>
          {{ cmnt.user_comment.username }}
          {{ cmnt.comment }}
        </li>
      </ul>
    {% endfor %}
{% endblock %}

templates/Blood_blog/Request_form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Colorlib Templates">
    <meta name="author" content="Colorlib">
    <meta name="keywords" content="Colorlib Templates">
    <!-- Icons font CSS-->
    <link href="{% static 'vendor/mdi-font/css/material-design-iconic-font.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/font-awesome-4.7/css/font-awesome.min.css' %}" rel="stylesheet" media="all">
    <!-- Font special for pages-->
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Vendor CSS-->
    <link href="{% static 'vendor/select2/select2.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/datepicker/daterangepicker.css' %}" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="{% static 'css/main.css' %}" rel="stylesheet" media="all">
</head>

<body>
    <div class="page-wrapper bg-gra-01 p-t-180 p-b-100 font-poppins">
        <div class="wrapper wrapper--w780">
            <div class="card card-3">
                <div class="card-heading" style="background-image:url('https://stmed.net/sites/default/files/blood-donor-month-wallpapers-28330-2217999.png')"></div>
                <div class="card-body">
                    <h2 class="title">Registration Info</h2>
                    <form method="POST" enctype="multipart/form-data">
                      {% csrf_token %}
                        <div class="input-group">
                            <input class="input--style-3" type="text" placeholder="Patient_name" name="name">
                        </div>
                        <div class="input-group">
                            <div class="rs-select2 js-select-simple select--no-search">
                                <select name="gender">
                                    <option disabled="disabled" selected="selected">Gender</option>
                                    <option>Male</option>
                                    <option>Female</option>
                                    <option>Other</option>
                                </select>
                                <div class="select-dropdown"></div>
                            </div>
                        </div>
                        <div class="input-group">
                            <input class="input--style-3" type="text" placeholder="blood group" name="blood">
                        </div>
                        <div class="input-group">
                            <input class="input--style-3" type="text" placeholder="Phone" name="phone">
                        </div>
                        <div class="input-group">
                            <div class="rs-select2 js-select-simple select--no-search">
                                <select name="state">
                                    <option disabled="disabled" selected="selected">State</option>
                                    <option>Andhra Pradesh</option>
                                    <option>Arunachal Pradesh</option>
                                    <option>Assam</option>
                                    <option>Bihar</option>
                                    <option>Goa</option>
                                    <option>Haryana</option>
                                    <option>Himachal Pradesh</option>
                                    <option>Jammu and Kashmir</option>
                                    <option>Jharkhand</option>
                                    <option>karnataka</option>
                                    <option>Kerala</option>
                                    <option>Madhya Pradesh</option>
                                    <option>Maharashtra</option>
                                    <option>Manipur</option>
                                    <option>Nagaland</option>
                                    <option>Odisha</option>
                                    <option>Telangana</option>
                                    <option>West Bengal</option>
                                </select>
                                <div class="select-dropdown"></div>
                            </div>
                        </div>
                        <div class="input-group">
                            <input class="input--style-3" type="number" placeholder="Amount of blood(ml)" name="Amount">
                        </div>
                        <div class="input-group">
                            <input class="input--style-3" type="textarea" placeholder="Reason" name="reason">
                        </div>
                        <div class="input-group">
                            <input class="input--style-3" type="date" name="date">
                        </div>
                            <input type="file" name="pic" accept="image/*">
                        <div class="p-t-10">
                            <button class="btn btn--pill btn--green" type="submit">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/select2/select2.min.js' %}"></script>
    <script src="{% static 'vendor/datepicker/moment.min.js' %}"></script>
    <script src="{% static 'vendor/datepicker/daterangepicker.js' %}"></script>

    <script src="{% static 'js/global.js' %}"></script>

</body>
</html>

templates/Blood_blog/base1.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head><meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type = "text/css" href='{% static "Blood_blog/css/main.css" %}'>

    <title></title>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
    $( function() {
      $( "#id_date" ).datepicker({ minDate: 0, maxDate: "+12M" , dateFormat: "yy-mm-dd"});
    } );
    </script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

  </head>
  <body>
    <nav class="navbar bg-dark navbar-dark">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#collapsibleNavbar" aria-expanded="false">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="navbar-collapse collapse" id="collapsibleNavbar" style="">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="javascript:void(0)">Link</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="javascript:void(0)">Link</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="javascript:void(0)">Link</a>
          </li>
        </ul>
      </div>
    </nav>
    <br>
    <main role="main" class="container">
    <div style="float:right">
        <div class="content-section">
          <h3>Our Sidebar</h3>
          <p class='text-muted'>You can put any information here you'd like.
            <ul class="list-group">
              <li class="list-group-item list-group-item-light">Latest Posts</li>
              <li class="list-group-item list-group-item-light">Announcements</li>
              <li class="list-group-item list-group-item-light">Calendars</li>
              <li class="list-group-item list-group-item-light">etc</li>
            </ul>
          </p>
        </div>
    </div>
        <div class="col-md-8">
          {% block content %}{% endblock %}
        </div>
    </main>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  </body>
</html>

templates/Blood_blog/home.html
{% extends "Blood_blog/base1.html" %}
{% block content %}
<a href="{% url 'Blood_blog:Blog' %}"><button type="button" name="button">Blog</button></a><br>
<a href=" {% url 'Blood_blog:DonationFormView' %} "><button type="button" name="button">Form</button></a>
{% endblock content %}

templates/Blood_blog/thank_you.html
{% extends 'userlogin/base.html' %}
{% load staticfiles %}

{% block content %}
<br><br><br>
    <script type="text/javascript" src="http://code.jquery.com/jquery-latest.min.js"></script>
    <script>
      $(function(){
          var time = 5;

          function redirect(){
            setTimeout(redirect,1000);
            $(".timer").html(time)
            if(time == 0)
            {
                window.location.href = 'http://127.0.0.1:8000/BloodRequest/home'
            }
            time--;
          }
          redirect()
        });
      </script>
    <center><img src="{% static "Blood_blog/images/loader.gif" %}" width="80px" height = "80px"></center>

   <center>  <h1>
     Thankyou for filling the form.<br>You'll be directed to our blog in
     <span class = "timer">0</span> seconds</h1></center><br><br><br>
      <br><br><br><br>
{% endblock %}