Donation_Kart/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import (PasswordResetView,PasswordResetDoneView,PasswordResetConfirmView,PasswordResetCompleteView)
from login import views
import userlogin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('bcamp/',include('bcamp.urls')),
    path('Bloodblog/',include('Blood_blog.urls')),
    path('userlogin/', include('userlogin.urls')),
    path('signup/',userlogin.views.signup,name="userlogin.signup"),
    path('login/',views.user_login,name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='login/home.html'),name='logout'),
    path('reset-password/', PasswordResetView.as_view(template_name='userlogin/password_reset_form.html',
                                                        email_template_name="userlogin/reset_password_email.html",
                                                        success_url="done/"), name="password_reset"),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='userlogin/password_reset_done.html'),
        name="password_reset_done"),
    path('reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/',
        PasswordResetConfirmView.as_view(template_name="userlogin/password_reset_confirm.html"),
        name="password_reset_confirm"),
    path(r'reset-password/complete/',
        PasswordResetCompleteView.as_view(template_name="userlogin/password_reset_complete.html"),
        name="password_reset_complete"),
    path('foodtruck/', include('foodtruck.urls')),
    # path('verf/', include('admin.urls')),
    path('Personal/',include('customer.urls')),
    path('User/',include('User.urls')),
    path('verf/', include('verifier.urls')),
    path('forum/', include('forum.urls')),
    path('reliffunds/', include('funds.urls')),
    path('paytm/', include('paytm.urls')),
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

User/urls.py
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from customer import views as cust

app_name='User'

urlpatterns = [
    path('home/',views.home,name="home"),
    path('events/',views.events,name="events"),
    path('cart/',views.cart,name="cart"),
    path('proceed/',views.proceed,name="proceed"),
    path('delete/<id>',views.delete,name="delete"),
    path('events/<id>',views.filter,name="filter"),
    path('Raiserequest/',views.Raiserequest,name="Raiserequest"),
    path('natdis/',views.natdis,name="natdis")
]

userlogin/urls.py
from django.urls import path,include, re_path
from django.conf.urls import url

from . import views

app_name="userlogin"

urlpatterns = [
    path('', views.index, name="userlogin.index"),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate,
        name='userlogin.activate'),
    path('profile/edit/', views.edit_profile, name='userlogin.edit_profile'),
    path('password/', views.change_password, name='userlogin.change_password'),
    path('signup/',views.signup,name='userlogin.signup')
]

userlogin/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.
class Profile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    address=models.CharField(max_length=100)
    city = models.CharField( max_length=100)
    country=models.CharField( max_length=100)
    pincode=models.CharField( max_length=10)



    picture=models.ImageField(upload_to='profile_image', default='static/userlogin/images/default-img.png')
    phone_number = models.CharField(max_length=10,
                                    validators=[
                                        RegexValidator(
                                            regex='^[1-9]{1}[0-9]{9}$',
                                            message='Enter a valid phone number',
                                            code='invalid_cell'
                                        ),
                                    ]
                                    )
    credits=models.IntegerField(default=0)
    reports=models.IntegerField(default=0)
    email_confirmed = models.BooleanField(default=False)
    user_choice = (
        ('V', 'Verifier'),
        ('C', 'Customer')
    )
    user_type=models.CharField(choices=user_choice, max_length=2, default='C')
    signedup_time=models.DateTimeField(auto_now_add=True)



    def __str__(self):  # __unicode__ for Python 2
        return self.user.username

userlogin/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from userlogin.models import Profile




class UserRegisterForm(UserCreationForm):

    #username = forms.CharField(label='Your name',max_length=100,widget=forms.TextInput(attrs={'class': 'form-control'})
    address=forms.CharField(min_length=1,max_length=100,required=True,widget=forms.TextInput())
    city = forms.CharField(min_length=1, max_length=100, required=True, widget=forms.TextInput())
    country=forms.CharField(min_length=1, max_length=100, required=True, widget=forms.TextInput())
    pincode=forms.CharField(label='zip')
    phone_number=forms.CharField(min_length=10,max_length=10,required=True,widget=forms.TextInput())
    picture=forms.ImageField( required=False, )
    email = forms.EmailField()

    def __init__(self, *args, **kwargs):
        super(UserRegisterForm, self).__init__(*args, **kwargs)

        for fieldname in ['username', 'password1', 'password2']:
            self.fields[fieldname].help_text = None

    class Meta:
        model = User
        fields = ['username', 'email','first_name','last_name', 'password1', 'password2']


class UserProfileForm(forms.ModelForm):



    class Meta:
        model=Profile
        fields=['phone_number','picture','address','city','country','pincode' ]


    def save(self, user=None):
        user_profile=super(UserProfileForm, self).save(commit=False)
        if user:
            user_profile.user=user
        user_profile.save()
        return user_profile


class EditProfileForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['first_name','last_name']

userlogin/views.py
from django.shortcuts import render,redirect
from userlogin.forms import UserRegisterForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages
from django.urls import reverse
from userlogin.models import Profile
from .forms import UserRegisterForm, EditProfileForm, UserProfileForm
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.core.mail import EmailMessage, send_mail
from django.contrib.auth import update_session_auth_hash
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm , PasswordChangeForm
# Create your views here.
def index(request):
    # Create your views here.

    return render(request, "userlogin/index.html")

def signup(request):
    # Create your views here.
    if request.method=='POST':

        form=UserRegisterForm(request.POST,request.FILES)
        if form.is_valid():

            username=form.cleaned_data.get('username')
            raw_password=form.cleaned_data.get('password1')
            new_user = form.save(commit=False)
            new_user.is_active=False
            new_user.save()
            new_user.refresh_from_db()  # load the profile instance created by the signal
            new_user.save()
            city = form.cleaned_data.get('city')
            address= form.cleaned_data.get('address')
            phone_number = form.cleaned_data.get('phone_number')
            pincode=form.cleaned_data.get('pincode')
            country = form.cleaned_data.get('country')
            picture = form.cleaned_data.get('picture')
            profile=Profile()
            profile.user = new_user




            profile.phone_number = phone_number
            profile.address = address
            if picture:
                profile.picture = picture
            profile.country = country
            profile.pincode=pincode
            profile.city=city
            profile.save()

            current_site = get_current_site(request)
            mail_subject = 'Activate your Donatekart account.'
            message = render_to_string('userlogin/acc_active_email.html', {
                'user': new_user,
                'domain': current_site.domain,
                'uid':urlsafe_base64_encode(force_bytes(new_user.pk)).decode(),
                'token':account_activation_token.make_token(new_user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                        mail_subject, message, to=[to_email]
            )
            email.send()
            return HttpResponse('Please confirm your email address to complete the registration')


        print(form)
    else:
        form = UserRegisterForm()
        print(form)

    return render(request, "userlogin/signup.html",{'form':form})

def edit_profile(request):
    if request.method == 'POST':
        passform = PasswordChangeForm(request.user, request.POST)
        user_form = EditProfileForm(request.POST,instance=request.user)
        print(user_form)
        profile_form = UserProfileForm(request.POST, request.FILES,instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            print(user_form)
            user_form.save()
            profile_form.save()
            messages.success(request, ('Your profile was successfully updated!'))
            return redirect('user_login:user_login.edit_profile')
        else:
            messages.error(request, ('Please correct the error below.'))
    else:
        print('outside')
        user_form = EditProfileForm(instance=request.user)
        profile_form = UserProfileForm(instance=request.user.profile)
        passform = PasswordChangeForm(request.user, request.POST)

    return render(request, 'userlogin/profile_edit2.html', {
            'user_form': user_form,
            'profile_form': profile_form,
            'passform':passform,
            'user':request.user
        })
        
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('login.view_profile')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)

    return render(request, 'userlogin/change_password.html', {
        'form': form
    })

def activate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.profile.email_confirmed=True
        user.save()
        user.profile.save()

        login(request, user)
        return redirect(reverse('userlogin:userlogin.edit_profile'))

    else:
        return HttpResponse('Activation link is invalid!')

templates/userlogin/acc_active_email.html
{% autoescape off %}

Hi {{ user.username }},
Please click on the link to confirm your registration,
http://127.0.0.1:8000{% url 'userlogin:userlogin.activate' uidb64=uid token=token %}
{% endautoescape %}

templates/userlogin/accounts.html
{% extends 'userlogin/base.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<a>
<h1>u r logged in</h1>
{% block body %}
<a href="http://127.0.0.1:8000/profile">viewprofile</a>
<a href="{% url 'foodtruck.foodrequest' %}">foodtruck </a>
{% endblock %}
</body>
</html>

templates/userlogin/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href={% static "login/css/style.css" %}>
    <link rel="stylesheet" href={% static "login/css/open-iconic-bootstrap.min.css" %}>
    <link rel="stylesheet" href={% static "login/css/animate.css" %}>
    <link rel="stylesheet" href={% static "login/css/flaticon.css" %}>
{% block extrahead %}

    {% endblock %}


</head>
<body>

  <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark " id="ftco-navbar">
    <div class="container">
      <a class="navbar-brand" href="index.html">Donation Kart</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="oi oi-menu"></span> Menu
      </button>

      <div class="collapse navbar-collapse" id="ftco-nav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active"><a href="{% url 'User:home' %}" class="nav-link">Home</a></li>

          <li class="nav-item active" ><a href="{% url 'User:events' %}" class="nav-link">Events</a></li>
          <li class="nav-item active" ><a href="{% url 'User:Raiserequest' %}" class="nav-link">Rise Request</a></li>
          <li class="nav-item active"><a href="{% url 'User:cart' %}" class="nav-link">Cart</a></li>
          <li class="nav-item active"><a href="{% url 'foodtruck:foodtruck.foodrequest' %}" class="nav-link">Foodtruck</a></li>
          <li class="nav-item active"><a href="{% url 'userlogin:userlogin.edit_profile' %}" class="nav-link">Profile</a></li>
          <li class="nav-item active"><a href="{% url 'logout' %}" class="nav-link">Logout</a></li>


        </ul>
      </div>
    </div>
  </nav>
{% block body %}

{% endblock %}


  <script src={% static "login/js/jquery.min.js" %}></script>
  <script src={% static "login/js/jquery-migrate-3.0.1.min.js" %}></script>
  <script src={% static "login/js/jquery.waypoints.min.js" %}></script>
  <script src={% static "login/js/jquery.stellar.min.js" %}></script>
  <script src={% static "login/js/owl.carousel.min.js" %}></script>
  <script src={% static "login/js/scrollax.min.js" %}></script>

  <script src={% static "login/js/bootstrap.min.js" %}></script>
  <script src={% static "login/js/jquery.easing.1.3.js" %}></script>
  <script src={% static  "login/js/jquery.easing.1.3.js" %}></script>


{% block script %}

{% endblock script %}




 </body>
</html>

templates/userlogin/change_password.html
<!DOCTYPE html>
{% load crispy_forms_tags %}
<head></head>
<body>

      <div class="w3-container w3-content" style="max-width:600px;margin-top:150px;margin-left: 350px;padding:10px; background-color:white; ">
        <div class="w3-col m7">
      <h1>Change Your Password</h1>
      <div>
          <form method="post">
                {% csrf_token %}
                {{ form|crispy }}<br>
                <button type="submit">Submit</button>
          </form>
          <br>
      </div>
      </div>
      </div>
</body>

templates/userlogin/index.html
<!DOCTYPE html>
{% load static %}
{% load staticfiles %}
{% load crispy_forms_tags %}
<html lang="en">
<head>
	<title>Login V5</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link rel="icon" type="image/png" href={% static "userlogin/images/icons/favicon.ico"%}/>

	<link rel="stylesheet" type="text/css" href={% static "userlogin/vendor/bootstrap/css/bootstrap.min.css"%}>

	<link rel="stylesheet" type="text/css" href={% static "userlogin/fonts/font-awesome-4.7.0/css/font-awesome.min.css"%}>

	<link rel="stylesheet" type="text/css" href={% static "userlogin/fonts/Linearicons-Free-v1.0.0/icon-font.min.css"%}>

	<link rel="stylesheet" type="text/css" href={% static "userlogin/vendor/animate/animate.css"%}>

	<link rel="stylesheet" type="text/css" href={% static "userlogin/vendor/css-hamburgers/hamburgers.min.css"%}>

	<link rel="stylesheet" type="text/css" href={% static "userlogin/vendor/animsition/css/animsition.min.css"%}>

	<link rel="stylesheet" type="text/css" href={% static "userlogin/vendor/select2/select2.min.css"%}>

	<link rel="stylesheet" type="text/css" href={% static "userlogin/vendor/daterangepicker/daterangepicker.css"%}>

	<link rel="stylesheet" type="text/css" href={% static "userlogin/css/util.css"%}>
	<link rel="stylesheet" type="text/css" href={% static "userlogin/css/main.css"%}>



</head>
<body>

	<div class="limiter">
		<div class="container-login100" style="background-image: url({% static 'userlogin/images/bg.png'%});">
			<div class="wrap-login100 p-l-110 p-r-110 p-t-62 p-b-33">
				<form class="login100-form validate-form flex-sb flex-w" method="POST">
					<span class="login100-form-title p-b-53">
						Login In With
					</span>


                    <div style="width:500px">

                            {% csrf_token %}
                            {{ form|crispy }}

                    </div>
<!--					<div class="p-t-31 p-b-9 ">

						<span class="txt1">
							Username
						</span>
					</div>

					<div class="wrap-input100 validate-input" data-validate = "Username is required">
						<input class="input100" type="text" name="uname" >
						<span class="focus-input100"></span>
					</div>

					<div class="p-t-13 p-b-9">
						<span class="txt1">
							Password
						</span>

						<a href="#" class="txt2 bo1 m-l-5">
							Forgot?
						</a>
					</div>
					<div class="wrap-input100 validate-input" data-validate = "Password is required">
						<input class="input100" type="password" name="pass" >
						<span class="focus-input100"></span>
					</div>
-->
					<div class="container-login100-form-btn m-t-17">
						<button class="login100-form-btn" type="submit ">
							LogIn
						</button>
					</div>

					<div class="w-full text-center p-t-55">
						<span class="txt2">
							Not a member?
						</span>

						<a href="#" class="txt2 bo1">
							Sign up now
						</a>
                        <a href="{% url 'password_reset' %}">reset password</a>
					</div>
				</form>
			</div>
		</div>
	</div>


	<div id="dropDownSelect1"></div>

	<script src={% static "userlogin/vendor/jquery/jquery-3.2.1.min.js"%}></script>

	<script src={% static "userlogin/vendor/animsition/js/animsition.min.js"%}></script>

	<script src={% static "userlogin/vendor/bootstrap/js/popper.js"%}></script>
	<script src={% static "userlogin/vendor/bootstrap/js/bootstrap.min.js"%}></script>

	<script src={% static "userlogin/vendor/select2/select2.min.js"%}></script>

	<script src={% static "userlogin/vendor/daterangepicker/moment.min.js"%}></script>
	<script src={% static "userlogin/vendor/daterangepicker/daterangepicker.js"%}></script>

	<script src={% static "userlogin/vendor/countdowntime/countdowntime.js"%}></script>

	<script src={% static "userlogin/js/main.js"%}></script>

</body>
</html>

templates/userlogin/password_reset_complete.html
  <p>
    Your password has been set. You may go ahead and <a href="{% url 'userlogin.change_password' %}">sign in</a> now.
  </p>

templates/userlogin/password_reset_confirm.html
{% load crispy_forms_tags %}


{% if validlink %}
    <h3>Change password</h3>
    <form method="post">
      {% csrf_token %}
      {{ form|crispy}}
      <button type="submit">Change password</button>
    </form>
  {% else %}
    <p>
      The password reset link was invalid, possibly because it has already been used.
      Please request a new password reset.
    </p>
  {% endif %}

templates/userlogin/password_reset_done.html
  <p>
    We've emailed you instructions for setting your password, if an account exists with the email you entered.
    You should receive them shortly.
  </p>
  <p>
    If you don't receive an email, please make sure you've entered the address you registered with,
    and check your spam folder.
  </p>

templates/userlogin/password_reset_form.html
{% load crispy_forms_tags %}


<h3>Forgot password</h3>
  <form method="post">
    {% csrf_token %}
    {{ form|crispy}}
    <button type="submit">Submit</button>
  </form>

templates/userlogin/profile_edit2.html
{% extends 'userlogin/base.html' %}
<!DOCTYPE html>
{% load staticfiles %}
{% load static %}
{% load crispy_forms_tags %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>donationkart</title>
    <link href='https://fonts.googleapis.com/css?family=Carter One' rel='stylesheet'>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static "userlogin/css/profile.css" %}">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">


  </head>
  <body style="width:100%;background-color:#f7f7f7;">
    {% block body %}
  <div class="row" style="border:2px solid #c1c1c1;padding:10px;">
        <div class="col-1"></div>
        <div class="col-3" style="border-right:1px solid #d5d5d5;">
          <center>
            <br>

            <img src="{{user.profile.picture.url}}" class="img-thumbnail" alt="error!" style="border-radius:50%;height:auto;width:100px;"><br><br>
              {{ profile_form.picture|as_crispy_field }}

          </center><br>
        </div>
        <div class="col-8">
          <p style="font-size:40px;">MY PROFILE</p>
          <table id="row">
            <th>
              <td class="box" style="width:15%;background-color:#e1e1e1"><button id="b1" style="width:100%;" type="button" class="btn btn-link" id="home">HOME</button> </td>
              <td class="box" style="width:15%;"><button id="b2" style="width:100%;" type="button" class="btn btn-link" id="address">ADDRESS</button> </td>
              <td class="box" style="width:15%;"><button id="b3" style="width:100%;" type="button" class="btn btn-link" id="setting">SETTINGS</button> </td>
            </th>
          </table>

          <div class="row">
                <form method="POST" >
                {% csrf_token %}
            <div class="col-12" id="div1">
              <br>

                <div class="row">
                  <div class="col-10">


                    {{ user_form.first_name|as_crispy_field }}
                  </div>
                  <div class="col-10">
                    {{ user_form.last_name|as_crispy_field }}

                  </div>
                </div>
                <div class="row">
                  <div class="col-10" >
                    {{ profile_form.phone_number|as_crispy_field }}
                  </div>
                </div><br>
                <div class="row">
                  <div class="col-10">
                    <center><input type="submit" class="btn btn-info" style="width:50%;" name="but" value="Save Changes"> </center>
                  </div>
                </div>

            </div>
            <div class="col-12" id="div2" style="display:none;">
              <br>

                <div class="row">
                  <div class="col-12">
                      {{ profile_form.address|as_crispy_field }}
                  </div>
                </div>
                <div class="row">
                  <div class="col-4">
                      {{ profile_form.city|as_crispy_field }}
                  </div>

                  <div class="col-4">
                      {{ profile_form.country|as_crispy_field }}
                  </div>
                  <div class="col-4">
                      {{ profile_form.pincode|as_crispy_field }}
                  </div>
                </div><br>
                <div class="row">
                  <div class="col-10">
                    <center><input type="submit" class="btn btn-info" style="width:50%;" name="but" value="Save Changes"> </center>
                  </div>
                </div>

            </div>
              </form>
            <div class="col-12" id="div3" style="display:none;">
              <br>
              <form method="POST" action="{% url 'userlogin:userlogin.change_password' %">
                {% csrf_token %}
                <h5 style="color:#13bef0">Change Password</h5><br>
                <div class="row">
                  <div class="col-5">
                    <label>EMAIL:</label>

                    <input class="form-control" type="email" value="{{ user.email }}" disabled>
                  </div>
                  <div class="col-5">
                    {{ passform.old_password|as_crispy_field }}
                  </div>
                </div>
                <div class="row">
                  <div class="col-5">
                    {{ passform.new_password1|as_crispy_field }}
                  </div>
                  <div class="col-5">
                    {{ passform.new_password2|as_crispy_field }}
                  </div>
                </div><br>
                <div class="row">
                  <div class="col-10">
                    <center><input type="submit" class="btn btn-info" style="width:50%;" name="settings" value="Save Changes"></center>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
    <script type="text/javascript">
      temp=0;
      var b1=document.getElementById('b1');
      var b2=document.getElementById('b2');
      var b3=document.getElementById('b3');
      var tabs=document.getElementsByClassName('box');
      var div1=document.getElementById('div1');
      var div2=document.getElementById('div2');
      var div3=document.getElementById('div3');


      window.onload=function(){
        b1.onclick=function(){
          b1.disabled=true;
          tabs[0].style.backgroundColor='#e5e5e5';
          div1.style.display='block';
          b2.disabled=false;
          tabs[1].style.backgroundColor='rgba(0,0,0,0)';
          div2.style.display='none';
          b3.disabled=false;
          tabs[2].style.backgroundColor='rgba(0,0,0,0)';
          div3.style.display='none';
        }
        b2.onclick=function(){
          b2.disabled=true;
          tabs[1].style.backgroundColor='#e5e5e5';
          div2.style.display='block';
          b1.disabled=false;
          tabs[0].style.backgroundColor='rgba(0,0,0,0)';
          div1.style.display='none';
          b3.disabled=false;
          tabs[2].style.backgroundColor='rgba(0,0,0,0)';
          div3.style.display='none';
        }
        b3.onclick=function(){
          b3.disabled=true;
          tabs[2].style.backgroundColor='#e5e5e5';
          div3.style.display='block';
          b2.disabled=false;
          tabs[1].style.backgroundColor='rgba(0,0,0,0)';
          div2.style.display='none';
          b1.disabled=false;
          tabs[0].style.backgroundColor='rgba(0,0,0,0)';
          div1.style.display='none';
        }
        b1.disabled=true;
      }
    </script>
    {% endblock %}
  </body>
</html>

templates/userlogin/reset_password_email.html
{% autoescape off %}
To initiate the password reset process for your {{ user.get_username }} TestSite Account,
click the link below:

{{ protocol }}://127.0.0.1:8000{% url 'password_reset_confirm' uidb64=uid token=token %}

If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead.

Sincerely,
The TestSite Team
{% endautoescape %}