Donation_Kart/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import (PasswordResetView,PasswordResetDoneView,PasswordResetConfirmView,PasswordResetCompleteView)
from login import views
import userlogin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('bcamp/',include('bcamp.urls')),
    path('Bloodblog/',include('Blood_blog.urls')),
    path('userlogin/', include('userlogin.urls')),
    path('signup/',userlogin.views.signup,name="userlogin.signup"),
    path('login/',views.user_login,name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='login/home.html'),name='logout'),
    path('reset-password/', PasswordResetView.as_view(template_name='userlogin/password_reset_form.html',
                                                        email_template_name="userlogin/reset_password_email.html",
                                                        success_url="done/"), name="password_reset"),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='userlogin/password_reset_done.html'),
        name="password_reset_done"),
    path('reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/',
        PasswordResetConfirmView.as_view(template_name="userlogin/password_reset_confirm.html"),
        name="password_reset_confirm"),
    path(r'reset-password/complete/',
        PasswordResetCompleteView.as_view(template_name="userlogin/password_reset_complete.html"),
        name="password_reset_complete"),
    path('foodtruck/', include('foodtruck.urls')),
    # path('verf/', include('admin.urls')),
    path('Personal/',include('customer.urls')),
    path('User/',include('User.urls')),
    path('verf/', include('verifier.urls')),
    path('forum/', include('forum.urls')),
    path('reliffunds/', include('funds.urls')),
    path('paytm/', include('paytm.urls')),
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

User/urls.py
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from customer import views as cust

app_name='User'

urlpatterns = [
    path('home/',views.home,name="home"),
    path('events/',views.events,name="events"),
    path('cart/',views.cart,name="cart"),
    path('proceed/',views.proceed,name="proceed"),
    path('delete/<id>',views.delete,name="delete"),
    path('events/<id>',views.filter,name="filter"),
    path('Raiserequest/',views.Raiserequest,name="Raiserequest"),
    path('natdis/',views.natdis,name="natdis")
]

customer/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name='customer'

urlpatterns=[
    path('', views.home, name='personal'),
]

Donation_Kart/customer/models.py
from django.db import models
from datetime import datetime
from django.core.validators import MinValueValidator
from django.contrib.auth.models import User

class request(models.Model):
    username = models.ForeignKey(User, on_delete=models.CASCADE)
    request_header = models.CharField(max_length=255)
    description = models.CharField(max_length=1024)
    amount = models.IntegerField(validators=[MinValueValidator(50000),])
    by_date = models.DateField()
    pic = models.ImageField(upload_to='requests', default='static/userlogin/images/default-img.png')
    request_date = models.DateField(default=datetime.now())

    def __str__(self):
        return self.request_header

User/models.py
from django.db import models
#from phonenumber_field.modelfields import PhoneNumberField
from userlogin.models import Profile
from django.contrib.auth.models import User
import sys
sys.setrecursionlimit(1000)
# Create your models here.


class Events_Supported(models.Model):
    type=models.CharField(max_length =50 , blank=False, null = False)
    subtype=models.CharField(max_length =50 , blank=False, null = False)


class Event(models.Model):
    eventid=models.AutoField(primary_key=True)
    requestedorganization=models.CharField(max_length =50 , blank=False, null = False)
    CHOICES = (('',"Select Type"),('1',"education"),('2',"NGO"),('3',"desasters"),)
    type=models.CharField(choices=CHOICES ,max_length =50, blank=False, null = False)
    SUB = (('',"Select Subtype"),('1',"stationary"),('2',"support"),)
    subtype=models.CharField(choices=SUB,max_length =50, blank=False, null = False)
    description=models.CharField(max_length =500 , blank=False, null = False)
    verifierassigned=models.CharField(max_length =10 , blank=False, null = True)
    status=models.BooleanField(default=False)
    verified=models.BooleanField(default=False)
    delivered=models.BooleanField(default=False)
    requesteddate=models.DateTimeField(auto_now_add=True,editable=False)
    enddate=models.DateTimeField(editable=True)
    img=models.ImageField(upload_to='images',blank=True)
    requesteditem=models.CharField(max_length =10 , blank=False, null = False)
    requestedquantity=models.PositiveIntegerField(default=0, blank=False, null = False)
    costperitem=models.PositiveIntegerField(default=0, blank=False, null = False)
    itemsremaining=models.PositiveIntegerField(default=0, blank=False, null = False)



class Donation(models.Model):
    donationid=models.AutoField(primary_key=True)
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    event=models.ForeignKey(Event, on_delete=models.CASCADE)
    date=models.DateTimeField(auto_now_add=True,editable=False)
    amount=models.PositiveIntegerField(default=0, blank=False, null = False)
    transactionid=models.CharField(max_length =50 , blank=False, null = False)
    item=models.CharField(max_length =10 , blank=False, null = False)
    Quantity=models.PositiveIntegerField(default=0, blank=False, null = False)
    description=models.CharField(max_length =200 , blank=False, null = False)

class Cart(models.Model):
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    event=models.ForeignKey(Event, on_delete=models.CASCADE)
    Quantity=models.PositiveIntegerField(default=0, blank=False, null = False)
    amount=models.PositiveIntegerField(default=0, blank=False, null = False)

    def delete(self):

        return 0

User/forms.py
from django import forms
from User.models import Event

class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        exclude = ['eventid','verifierassigned','status','verified','deliverd','requesteddate','itemsremaining']
        CHOICES = (('',("Select Type")),('1',("education")),('2',("NGO")),('3',("desasters")),)
        SUB = (('',("Select Subtype")),('1',("stationary")),('2',("support")),)



        labels = {
            'requestedorganization':'',
            'type':'',
            'subtype':'',
            'description':'',
            'enddate':'',
            'img':'',
            'requesteditem':'',
            'requestedquantity':'',
            'costperitem':'',
        }

User/views.py
from django.core.mail import send_mail
from django.conf import settings
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Event,Events_Supported,Cart,Donation
from userlogin.models import Profile
from django.contrib.auth.decorators import login_required
from django.db import transaction,connection
from User.forms import EventForm
from funds.models import funds, Images


@login_required(login_url='login')
def home(request):
    return render(request,'User/home.html')

@login_required
def Raiserequest(request):
    print('a')
    eventform=EventForm()
    if request.method=='POST':
        eventform=EventForm(request.POST)
        if eventform.is_valid():
            print('x')
            requestedorganization=eventform.cleaned_data.get['requestedorganization']
            type=eventform.cleaned_data.get['type']
            subtype=eventform.cleaned_data.get['subtype']
            description=eventform.cleaned_data.get['description']
            enddate=eventform.cleaned_data.get['enddate']
            image=eventform.cleaned_data.get['img']
            requesteditem=eventform.cleaned_data.get['requesteditem']
            requestedquantity=eventform.cleaned_data.get['requestedquantity']
            costperitem=eventform.cleaned_data.get['costperitem']
            eventdata=Event.objects.create(requestedorganization=requestedorganization,type=type,subtype=subtype,description=description,enddate=enddate,image=image,requesteditem=requesteditem,requestedquantity=requestedquantity,costperitem=costperitem)
            eventdata.save()
            return redirect('User:home')
        else:
            print('y')
            eventform=EventForm(request.POST)
            return render(request,'User/riserequest.html',{'eventform':eventform})
    else:
        print('z')
        return render(request,'User/riserequest.html',{'eventform':eventform})

@login_required(login_url='login')
def events(request):
    eventslist=Events_Supported.objects.all()
    eventsset=[]
    for e in eventslist:
        eventsset.append(e.type)
    #eventslist=list(set(eventsset))
    cursor=connection.cursor()
    cursor.callproc('eventfilter',["all",])
    events_eme = (cursor.fetchall())
    # Event.objects.filter(completed=False).filter(verified=True).order_by('enddate')
    events_eme_list=[]
    for e in events_eme:
        temp=Event.objects.filter(eventid=e[0])
        dlist=[]
        for t in temp:
            dlist.append(t)
        donated_quantity=0
        for d in Donation.objects.filter(event_id=e[0]):
            donated_quantity+=d.Quantity
        dlist.append(donated_quantity)
        dlist.append(e[13])
        dlist.append(100-int(e[15])*100/e[14])
        dlist.append(e[14]-donated_quantity)
        dlist.append((e[14]-donated_quantity))
        events_eme_list.append(tuple(dlist))
    events_eme_list[:12]
    return render(request,'User/event2.html',context={'eventslist':eventslist,'events':events_eme_list,})


def natdis(request):
    relif = funds.objects.all()
    imgs = funds.objects.all()
    return render(request,'User/natdis.html',context={'events':relif,'imgs':imgs})


@login_required(login_url='login')
def cart(request):
    user=request.user
    if(request.POST):
        eventID=int(request.POST['eventid'])
        quantity=int(request.POST['quantity'])
        event=0
        for e in Event.objects.filter(eventid=eventID):
            event=e
        cartlist=Cart.objects.filter(user=user)
        flag=0
        for c in cartlist:
            if c.event==event:
                #quantity+=c.Quantity
                #amount=200
                #Cart.objects.filter(user=user).filter(event=event).update(Quantity=quantity)
                #Cart.objects.filter(user=user).filter(event=event).update(amount=amount)
                flag=1
        if flag==0:
            amount=quantity*event.costperitem
            Cart.objects.create(event=event,user=request.user,Quantity=quantity,amount=amount)
    cartcost=0
    cartlist=list()
    for c in Cart.objects.filter(user=user):
        for e in Event.objects.filter(verified=True):
            if c.event==e:
                cartlist.append([c,e])
                cartcost+=c.Quantity*e.costperitem
    #print(cartlist)
    count=len(cartlist)

    return render(request,'User/cart.html',context={'cartlist':cartlist,'count':count,'cartcost':cartcost})

@login_required(login_url='login')
def delete(request,id):
    event=0
    for e in Event.objects.filter(eventid=id):
        event=e
    cartItems = Cart.objects.filter(user=request.user,event=event)
    cartItems.delete()
    return cart(request)

@login_required(login_url='login')
def filter(request,id):
    eventslist=Events_Supported.objects.all()
    eventsset=[]
    for e in eventslist:
        eventsset.append(e.type)

    type=id
    print(type)
    cursor=connection.cursor()
    cursor.callproc('eventfilter',[type,])
    events_eme = (cursor.fetchall())
    # Event.objects.filter(completed=False).filter(verified=True).order_by('enddate')
    events_eme_list=[]
    for e in events_eme:
        temp=Event.objects.filter(eventid=e[0])
        dlist=[]
        for t in temp:
            dlist.append(t)
        donated_quantity=0
        for d in Donation.objects.filter(event_id=e[0]):
            donated_quantity+=d.Quantity
        dlist.append(donated_quantity)
        dlist.append(e[13])
        dlist.append(100-int(e[15])*100/e[14])
        dlist.append(e[14]-donated_quantity)
        events_eme_list.append(tuple(dlist))
    events_eme_list[:12]
    return events(request)

@login_required(login_url='login')
def proceed(request):
    user=request.user
    count=Cart.objects.filter(user=user).count()
    if count and payment(request):
        for c in Cart.objects.filter(user=user):
            for e in Event.objects.filter(verified=True):
                if c.event==e:
                    itemsremaining=e.itemsremaining-c.Quantity
                    Event.objects.filter(eventid=e.eventid).update(itemsremaining=itemsremaining)
                    Cart.objects.filter(user=user).delete()
                    return redirect('http://127.0.0.1:8000/paytm/payment/')
    return home(request)


def payment(request):
    return True

Donation_Kart/templates/User/events.html
{% extends 'userlogin/base.html' %}
{% load static %}

<!DOCTYPE html>
<html>
<head>
  {% block extrahead %}
  <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<style>
* {box-sizing: border-box;}

body {
  margin: 0;
  font-family: Arial, Helvetica, sans-serif;
}

#div1 {
  font-size:40px;
}
}
</style>
<style>
.card {
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
  width:450px;
  height: 750px;
  margin: 2.5rem;
  text-align: center;
  font-family: arial;
  float:left;
}

.title {
  color: grey;
  font-size: 18px;
}


  .quantity {
    position: relative;
  }

  input[type=number]::-webkit-inner-spin-button,
  input[type=number]::-webkit-outer-spin-button
  {
    -webkit-appearance: none;
    margin: 0;
  }

  input[type=number]
  {
    -moz-appearance: textfield;
  }

  .quantity input {
    width: 100px;
    height: 50px;
    line-height: 1.65;
    float: left;
    display: block;
    padding: 0;
    margin: 0;
    padding-left: 20px;
    border: 1px solid #eee;
    background-color:#e6e6e6;
  }

  .quantity input:focus {
    outline: 0;
  }

  .quantity-nav {
    float: left;
    position: relative;
    height: 50px;
  }

  .quantity-button {
    position: relative;
    cursor: pointer;
    border-left: 0px #eee;
    width: 30px;
    text-align: center;
    color: #333;
    font-size: 17px;
    font-family: "Trebuchet MS", Helvetica, sans-serif !important;
    line-height: 1.7;
    -webkit-transform: translateX(-100%);
    transform: translateX(-100%);
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    -o-user-select: none;
    user-select: none;
  }

  .quantity-button.quantity-up {
    position: absolute;
    height: 50%;
    top: 0;
    background-color:#32CD32;
    border-bottom: 1px solid #eee;
  }

  .quantity-button.quantity-down {
    position: absolute;
    bottom: -1px;
    background-color:grey;
    height: 50%;
  }


input[type=number]::-webkit-inner-spin-button {
    -webkit-appearance: none;
  }

.cartbtn{
  background-color: #FF8C00;
  border: none;
  width:300px;
  color: white;
  padding: 20px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 20px;
  margin: 4px 2px;
  cursor: pointer;
  border-radius: 20%;


}

.cartbtn:hover{
  background-color:#e36100 ;
  width:350px;
  border-radius: 30%;
  transition: 0.4s;
}


</style>
{% endblock %}
</head>
<body style="background-color:#e6e6e6;">

{% block body %}

<table style="width:100%;padding:50px 0px 50px;margin-top:300px;" >
  <tr>
    <td style="width:70%;padding:50px 100px  150px 200px">


{% for event in events %}
<form method="POST" action="{% url 'User:cart' %}">
{% csrf_token %}
    <div class="card">
    <div style="border-bottom: 3px solid #e6e6e6;">
    <img src="{{event.0.img.url}}" alt="pic" style="width:100%;height:250px;padding:15px 15px 15px 15px">
    </div>
    <div style="border-bottom: 3px solid #e6e6e6;padding:10px 5px 10px 5px">
    <h1 style="color: #FF8C00">{{event.0.requestedorganization}}</h1>
    <p class="title" >{{event.0.description}}</p>
    </div>
    <div style="border-bottom: 1px solid #e6e6e6;padding:10px 5px 10px 5px">
    <h3>{{event.0.subtype}} : {{event.0.requesteditem}}</h3>
<center>
  <div class="container" style="padding:20px 30px 20px 30px ">
    <div class="progress"  style="height:25px">
      <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width:{{event.3}}%;height:25px;background-color:green;color:black">
        {{event.3}}% Complete
      </div>
    </div>
  </div>
</center>
</div>
<center>
    <h4 style="padding:10px;color: #4dff4d">End Date : {{event.0.enddate}}</h4>
</center>
<center style="padding:5px 5px 5px ;">
<b>Quantity : </b>
<input type="number" name="quantity" min="1" max={{event.2}}  id="{{event.0.eventid}}" style="padding:20px 30px 20px ;" placeholder="0" required/>
<b style="color: #4dff4d;padding:0px 20px;font-size: 20px;">  {{event.0.costperitem}} <i>Rs</i>/<i style="font-size: 15px;">product</i> </b>
<br><br>
<input  name="eventid" value="{{event.0.eventid}}" type="hidden" />
<button  class="cartbtn" type="submit" id="submit" value="submit"  name="addcart" ><b>Add To Cart</b></button>
</center>
  </div>
</form>
{% endfor %}

</td>
    <td valign="top" style="width:20%;padding:50px 10px  50px 10px">
      <h2 style="color:grey">Categories </h2><br>
      <div style="border-top: 3px solid #bfbfbf;border-bottom: 3px solid #bfbfbf;padding:30px 0px 30px">
      <a href="{% url 'User:events' %}" style="padding:20px 10px;color:#8c8c8c;">All</a><br>
      <a href="{% url 'User:filter' "education" %}" style="padding:20px 10px;color:#8c8c8c;">Education</a><br>
      <a href="{% url 'User:filter' "Ngo" %}" style="padding:20px 10px;color:#8c8c8c;">Support NGOs</a><br>
      <a href="{% url 'foodtruck:foodtruck.foodrequest' %}" style="padding:20px 10px;color:#8c8c8c;">Food</a><br>
      <a href="{% url 'customer:personal' %}" style="padding:20px 10px;color:#8c8c8c;">Personal</a><br>
      <a href="#" style="padding:20px 10px;color:#8c8c8c;">Blood</a><br>
      </div><br>
      <h2 style="color:grey;padding:70px 0px 0px 0px;">Donor Voice </h2><br>
      <div style="border-top: 3px solid #bfbfbf;border-bottom: 3px solid #bfbfbf;padding:30px 0px 30px">

      </div>
    </td>
<td style="width:20%"></td>
  </tr>
</table>
<!-- <div style="margin-top:210px;padding:15px 15px 2500px;font-size:30px"></div> -->

<script>
// When the user scrolls down 80px from the top of the document, resize the navbar's padding and the logo's font size
window.onscroll = function() {scrollFunction()};

function scrollFunction() {
  if (document.body.scrollTop > 50 || document.documentElement.scrollTop > 50) {
    document.getElementById("navbar").style.padding = "20px 100px";
    document.getElementById("navbar").style.top = "0";
    document.getElementById("logo").style.fontSize = "40px";
  } else {
    document.getElementById("navbar").style.padding = "70px 100px";
    document.getElementById("logo").style.fontSize = "60px";
    document.getElementById("navbar").style.top = "50px";
  }
}
</script>

<script>
function hourglass() {
  var a;
  a = document.getElementById("div1");
  a.innerHTML = "&#xf251;";
  setTimeout(function () {
      a.innerHTML = "&#xf252;";
    }, 1000);
  setTimeout(function () {
      a.innerHTML = "&#xf253;";
    }, 2000);
}
hourglass();
setInterval(hourglass, 3000);
</script>
{% endblock %}
</body>
</html>