Donation_Kart/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import (PasswordResetView,PasswordResetDoneView,PasswordResetConfirmView,PasswordResetCompleteView)
from login import views
import userlogin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('bcamp/',include('bcamp.urls')),
    path('Bloodblog/',include('Blood_blog.urls')),
    path('userlogin/', include('userlogin.urls')),
    path('signup/',userlogin.views.signup,name="userlogin.signup"),
    path('login/',views.user_login,name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='login/home.html'),name='logout'),
    path('reset-password/', PasswordResetView.as_view(template_name='userlogin/password_reset_form.html',
                                                        email_template_name="userlogin/reset_password_email.html",
                                                        success_url="done/"), name="password_reset"),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='userlogin/password_reset_done.html'),
        name="password_reset_done"),
    path('reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/',
        PasswordResetConfirmView.as_view(template_name="userlogin/password_reset_confirm.html"),
        name="password_reset_confirm"),
    path(r'reset-password/complete/',
        PasswordResetCompleteView.as_view(template_name="userlogin/password_reset_complete.html"),
        name="password_reset_complete"),
    path('foodtruck/', include('foodtruck.urls')),
    # path('verf/', include('admin.urls')),
    path('Personal/',include('customer.urls')),
    path('User/',include('User.urls')),
    path('verf/', include('verifier.urls')),
    path('forum/', include('forum.urls')),
    path('reliffunds/', include('funds.urls')),
    path('paytm/', include('paytm.urls')),
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

User/urls.py
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from customer import views as cust

app_name='User'

urlpatterns = [
    path('home/',views.home,name="home"),
    path('events/',views.events,name="events"),
    path('cart/',views.cart,name="cart"),
    path('proceed/',views.proceed,name="proceed"),
    path('delete/<id>',views.delete,name="delete"),
    path('events/<id>',views.filter,name="filter"),
    path('Raiserequest/',views.Raiserequest,name="Raiserequest"),
    path('natdis/',views.natdis,name="natdis")
]

customer/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name='customer'

urlpatterns=[
    path('', views.home, name='personal'),
]

forum/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name='forum'

urlpatterns=[
    path('home_with_pk/(?P<pk>\d+)/', views.home, name='home_with_pk'),
]

login/urls.py
from django.urls import path,include, re_path
from . import views

app_name = 'login'

urlpatterns = [
    re_path('^$', views.home, name="login.home"),
    path('accounts/', views.user_login, name="login.user_login"),
    path('logout/',views.logoutuser, name="logout")

]

paytm/urls.py
from django.conf.urls import include, url
from paytm import views as paytm_views

app_name="paytm"

urlpatterns = [
    # Examples:
    url(r'^$', paytm_views.home, name='paytm.home'),
    url(r'^payment/', paytm_views.payment, name='payment'),
    url(r'^response/', paytm_views.response, name='response'),
]

forum/models.py
from django.db import models
from datetime import datetime
from django.core.validators import MinValueValidator
from django.contrib.auth.models import User

class forumdetails(models.Model):
    username = models.ForeignKey(User, on_delete=models.CASCADE)
    request_header = models.CharField(max_length=255)
    description = models.CharField(max_length=1024)
    amount = models.IntegerField(validators=[MinValueValidator(50000),])
    pic = models.ImageField(upload_to='requests', default='static/userlogin/images/default-img.png')
    by_date = models.DateField()

    def __str__(self):
        return self.request_header

class commentinfo(models.Model):
    to = models.ForeignKey(forumdetails, on_delete=models.CASCADE)
    message = models.CharField(max_length=1024)
    by = models.ForeignKey(User, on_delete=models.CASCADE)

forum/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from forum.models import forumdetails, commentinfo
from django.contrib.auth.decorators import login_required

@login_required
def home(request, pk):
    if pk:
        if request.method == 'POST':
            if len(request.POST['msg']) > 1:
                c_user = request.user
                new_comment = commentinfo(message = request.POST['msg'], by = c_user )
                new_comment.to = forumdetails.objects.get(pk=pk)
                new_comment.save()
        reqs = forumdetails.objects.all()
        forum = forumdetails.objects.get(pk=pk)
        comments = commentinfo.objects.filter(to = forum.pk)
        print(forum)
        print(comments)
        return render(request, 'forum/base.html', {'reqs':reqs, 'forum':forum, 'comments':comments})
    else:
        return HttpResponseRedirect(reverse('cus_login:home'));

templates/forum/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load crispy_forms_tags %}
<html lang="en" dir="ltr">
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta charset="utf-8">
    <link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.7.0/css/all.css' integrity='sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ' crossorigin='anonymous'>
    <link rel="shortcut icon" type="image/x-icon" href="../../static/images/favicon.ico" />
    <link href='https://fonts.googleapis.com/css?family=Acme' rel='stylesheet'>
    <link rel="stylesheet" href="../../static/css/home2.css">
    <title>Fund Hub</title>
  </head>
  <body>
    <img style="opacity:0.6;width:100%;position:fixed;height:700px;z-index:0;" src="https://cdn.pixabay.com/photo/2017/06/27/11/48/team-spirit-2447163_960_720.jpg" alt="ERROR!">
    <div class="container-fluid">
      <div class="row" style="padding-top:12px;">
        <div class="col-4">
          <h2 style="font-family:fantasy;color:#f3f3f3;">FUND HUB</h2>
        </div>
        <div style="text-align:right;" class="col-8">
          <span><a href="{% url 'login:logout' %}"><button class="btn btn-light" type="button" name="button">Logout</button></a></span>
        </div>
      </div>
      <br>
      <div style="margin-top: 1%;border-radius: 1%;padding:30px;border:1px solid #333333;background: black;">
        <div class="row">
          <div class="col-3">
            <h3 style="text-align:center;color:#70ffd1">Also Checkout!</h3>
            <table class="table table-striped" style="margin-top:7%;">
              <tbody style="overflow-y:scroll;height:130px;display:block;">
                {% for a in reqs %}
                  <tr>
                    <td><a style="text-decoration:none;color:white;font-size:18px;" href="{% url 'forum:home_with_pk' pk=a.pk %}">{{ a.request_header }}</a></td>
                    <td><a style="text-decoration:none;color:white;font-size:18px;" href="{% url 'forum:home_with_pk' pk=a.pk %}">{{ a.by_date }}</a></td>
                  </tr>
                {% endfor %}
              </tbody>
            </table><hr size="3px">
            <img src="/media/{{ forum.pic }}" alt="ERROR!" style="width:80%;">
          </div>
          <div class="col-6">
            <h3 style="font-family: sans-serif;text-align: center;width:100%;color:#f5f5f5;">{{ forum.request_header }}</h3>
            <div id="scroll" style="border-radius: 1%;background-color:rgba(255,255,255,0.8);height:260px;overflow-y:scroll;overflow-x:hidden;">
              <div class="row" style="padding:23px;">
                <ul style="list-style-type:none;">
                  {% for i in comments %}
                  {% if i.by == forum.username and i.message|length > 1 %}
                  <li><p style="border-radius: 3%;width:100%;margin-left: 300%;font-size: 16px;opacity: 1;background-color:rgba(10, 163,168,1);color:#f3f3f3;padding:8px;">{{ i.message }}</p></li>
                  {% elif i.message|length > 1 %}
                  <li><p style="border-radius: 3%;font-size: 16px;opacity: 1;background-color:rgba(45,73,255, 1);color:#f3f3f3;padding:8px;">{{ i.message }}
                    <br>
                    -{{ i.by }}
                  </p></li>
                  {% endif %}
                  {% endfor %}
                </ul>
              </div>
            </div>
            <form method="POST">
              {% csrf_token %}
              <br>
              <table style="width:100%;">
                <tr>
                  <td style="width:80%;">
                    <div class="form-group">
                      <label for="txt" style="font-size:17px;color:#222222;"> <b>Send Wishes</b></label>
                      <textarea style="width:95%;" class="form-control" id="txt" rows="3" name="msg" placeholder="Message..."></textarea>
                    </div>
                  </td>
                  <td style="width:15%">
                    <a href="{% url 'paytm:payment' %}"><button onclick="" style="margin-bottom:10px;margin-top:17px;width:90%" class="btn btn-warning" type="button" name="button">Payment</button></a> 
                    <input style="width:90%;" class="btn btn-primary" type="submit" name="submit" value="Submit">
                  </td>
                </tr>
              </table>
            </form>
          </div>
          <div class="col-3" style="color:#f9f9f9;">
            <br><br>
            <p style="font-size:18px;float:right;">{{ forum.username }}</p><br><br>
            <p style="text-align:justify;">{{ forum.description }}</p>
            <p style="font-size:30px;text-align:center;">{{ forum.amount }} &#8377;</p>
            <p style="display:none" id="time">{{ forum.by_date }}</p>
            <p id="show" style="text-align:center;font-size:25px;"></p><br><br><br>
            <button style="float:right;" type="button" class="btn btn-link btn-lg"><a href="{% url 'customer:personal' %}">Go Back</a></button>
          </div>
        </div>
      </div>
      <br>
    </div>
    <script>

      var countDownDate = new Date(document.getElementById('time').innerHTML).getTime();
      var x = setInterval(function() {
        var now = new Date().getTime();
        var distance = countDownDate - now;
        var days = Math.floor(distance / (1000 * 60 * 60 * 24));
        var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
        var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
        var seconds = Math.floor((distance % (1000 * 60)) / 1000);
        document.getElementById("show").innerHTML = days + "d " + hours + "h "
        + minutes + "m " + seconds + "s ";
        if (distance < 0) {
          clearInterval(x);
          document.getElementById("show").innerHTML = "EXPIRED";
        }
      }, 1000);

      var objDiv = document.getElementById("scroll");
      objDiv.scrollTop = objDiv.scrollHeight;

    </script>
  </body>
</html>